module.exports = {
  SERVER_LISTEN: 'REXPRESS_SERVER_LISTEN',
  SERVER_CLOSE: 'REXPRESS_SERVER_CLOSE',
  SERVER_LISTEN_FAILED: 'REXPRESS_SERVER_LISTEN_FAILED',
  SERVER_CLOSE_FAILED: 'REXPRESS_SERVER_CLOSE_FAILED',
  REQUEST_START: 'REXPRESS_REQUEST_START',
  REQUEST_CLOSED: 'REXPRESS_REQUEST_CLOSED',
  REQUEST_ABORT: 'REXPRESS_REQUEST_ABORT',
  RESPONSE_WRITE_HEAD: 'REXPRESS_RESPONSE_WRITE_HEAD',
  RESPONSE_END: 'REXPRESS_RESPONSE_END',
  RESPONSE_CLOSED: 'REXPRESS_RESPONSE_CLOSED',
  RESPONSE_FINISH: 'REXPRESS_RESPONSE_FINISH',
};
