module.exports = {
  LISTEN: 'REXPRESS_SERVER_LISTEN',
  CLOSE: 'REXPRESS_SERVER_CLOSE',
  LISTEN_FAILED: 'REXPRESS_SERVER_LISTEN_FAILED',
  CLOSE_FAILED: 'REXPRESS_SERVER_CLOSE_FAILED',
  ADD: 'REXPRESS_SERVER_ADD',
  REMOVE: 'REXPRESS_SERVER_REMOVE',
};
