module.exports = {
  LISTEN: 'REXPRESS_SERVER_LISTEN',
  CLOSE: 'REXPRESS_SERVER_CLOSE',
  LISTEN_FAILED: 'REXPRESS_SERVER_LISTEN_FAILED',
  CLOSE_FAILED: 'REXPRESS_SERVER_CLOSE_FAILED',
  ADD: 'REXPRESS_SERVER_ADD',
  REMOVE: 'REXPRESS_SERVER_REMOVE',
  REQUEST_START: 'REXPRESS_REQUEST_START',
  REQUEST_CLOSED: 'REXPRESS_REQUEST_CLOSED',
  REQUEST_FINISH: 'REXPRESS_REQUEST_FINISH',
  RESPONSE_WRITE_HEAD: 'REXPRESS_RESPONSE_WRITE_HEAD',
  REQUEST_END: 'REXPRESS_REQUEST_END',
};
